// ThingKind constants (used as string values)
export const ThingKind = {
  NETWORK_NODE: "network.node",
  NETWORK_PEER: "network.peer",
  NETWORK_ROUTE: "network.route",
  NETWORK_RELAY: "network.relay",
  NETWORK_DIRECTORY: "network.directory",
  CRYPTO_HANDSHAKE: "crypto.handshake",
  CRYPTO_SESSION: "crypto.session",
  CRYPTO_CHANNEL: "crypto.channel",
  MESSAGE: "message",
  MESSAGE_ENVELOPE: "message.envelope",
  MESSAGE_RECEIPT: "message.receipt",
  AGENT: "agent",
  AGENT_CAPABILITY: "agent.capability",
  WORK_ORDER: "work.order",
  WORK_RESULT: "work.result",
  TRUST_EVENT: "trust.event",
  TRUST_LEDGER: "trust.ledger",
  AUDIT_LOG: "audit.log",
};
